PetParadise.Web/Areas/Administration/Controllers/ReservationsController.cs
namespace PetParadise.Web.Areas.Administration.Controllers
{
    using System.Collections;
    using System.Globalization;
    using System.Linq;
    using System.Threading;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using Kendo.Mvc.Extensions;
    using Kendo.Mvc.UI;

    using PetParadise.Data.Models;
    using PetParadise.Data;
    using PetParadise.Web.Areas.Administration.Controllers.Base;

    using Model = PetParadise.Data.Models.Reservation;
    using ViewModel = PetParadise.Web.Areas.Administration.ViewModels.Reservations.ReservationViewModel;
    
    public class ReservationsController : KendoGridAdministrationController
    {
        public ReservationsController(IPetParadiseData data)
            : base(data)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
        }

        public ActionResult Index()
        {
            return View();
        }

        protected override IEnumerable GetData()
        {
            return this.Data.Reservations
                .All()
                .Project()
                .To<ViewModel>();
        }

        protected override T GetById<T>(object id)
        {
            return this.Data.Reservations.GetById(id) as T;
        }

        [HttpPost]
        public ActionResult Create([DataSourceRequest]DataSourceRequest request, ViewModel model)
        {
            var dbModel = base.Create<Model>(model);
            if (dbModel != null)
            {
                model.Id = dbModel.Id;
            }

            return this.GridOperation(model, request);
        }

        [HttpPost]
        public ActionResult Update([DataSourceRequest]DataSourceRequest request, ViewModel model)
        {
            base.Update<Model, ViewModel>(model, model.Id);
            return this.GridOperation(model, request);
        }

        [HttpPost]
        public ActionResult Destroy([DataSourceRequest]DataSourceRequest request, ViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                this.Data.Reservations.Delete(model.Id);
                this.Data.SaveChanges();
            }

            return this.GridOperation(model, request);
        }
    }
}

PetParadise.Web/Controllers/BreedsController.cs
using PetParadise.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetParadise.Web.Controllers
{
    public class BreedsController : BaseController
    {
        public BreedsController(IPetParadiseData data)
            : base(data)
        {
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

PetParadise.Web/Controllers/SpeciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PetParadise.Data;
using PetParadise.Data.Models;

namespace PetParadise.Web.Controllers
{
    public class SpeciesController : BaseController
    {
        private PetParadiseDbContext db = new PetParadiseDbContext();

        public SpeciesController(IPetParadiseData data)
            : base(data)
        {
        }

        // GET: Species
        public ActionResult Index()
        {
            return View(db.Species.ToList());
        }

        // GET: Species/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Species species = db.Species.Find(id);
            if (species == null)
            {
                return HttpNotFound();
            }
            return View(species);
        }

        // GET: Species/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Species/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Information")] Species species)
        {
            if (ModelState.IsValid)
            {
                db.Species.Add(species);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(species);
        }

        // GET: Species/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Species species = db.Species.Find(id);
            if (species == null)
            {
                return HttpNotFound();
            }
            return View(species);
        }

        // POST: Species/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Information")] Species species)
        {
            if (ModelState.IsValid)
            {
                db.Entry(species).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(species);
        }

        // GET: Species/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Species species = db.Species.Find(id);
            if (species == null)
            {
                return HttpNotFound();
            }
            return View(species);
        }

        // POST: Species/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Species species = db.Species.Find(id);
            db.Species.Remove(species);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PetParadise.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pet Paradise</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/kendo")
    @RenderSection("styles", required: false)
    @Styles.Render("~/Content/custom")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("Pet Paradise", "Index", "Home", new { Area = string.Empty }, new { @class = "navbar-brand page-logo" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="menu">
                    <li>@Html.ActionLink("Начало", "Index", "Home", new { Area = string.Empty }, new { @class = "" })</li>
                    <li>@Html.ActionLink("Всички любимци", "All", "Pets", new { Area = string.Empty }, new { @class = "" })</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            Още...
                            <ul>
                                <li>@Html.ActionLink("Добави любимец", "Add", "Pets", new { Area = string.Empty }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Нова резервация", "Create", "Reservations", new { Area = string.Empty }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Моите резервации", "MyReservations", "Reservations", new { Area = string.Empty }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Породи", "Index", "Breeds", new { Area = string.Empty }, new { @class = "" })</li>
                            </ul>
                        </li>
                        if (User.IsInRole("Admin"))
                        {
                            <li>
                                Администрация
                                <ul>
                                    <li>@Html.ActionLink("Видове", "Index", "Species", new { Area = string.Empty }, new { @class = "" })</li>
                                    <li>@Html.ActionLink("Резервации", "Index", "Reservations", new { Area = "Administration" }, new { @class = "" })</li>
                                </ul>
                            </li>
                        }
                    }
                    <li>@Html.ActionLink("За нас", "About", "Home", new { Area = string.Empty }, new { @class = "" })</li>
                    <li>@Html.ActionLink("Контакти", "Contact", "Home", new { Area = string.Empty }, new { @class = "" })</li>
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>@DateTime.Now.Year - Pet Paradise&reg;</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendo")
    @RenderSection("scripts", required: false)
    <script>
        $(function () {
            $('#menu').kendoMenu();
        })
    </script>
</body>
</html>